name: Build TDLib for amd64 / arm64 / armhf

on:
  push:
    branches: [main]        # adjust as needed
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            toolchain: ""
          - arch: arm64
            toolchain: .github/toolchains/arm64.cmake
          - arch: armhf
            toolchain: .github/toolchains/armhf.cmake

    steps:
      - uses: actions/checkout@v4

      - name: Install build deps + cross compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make git zlib1g-dev libssl-dev gperf php-cli \
            cmake clang-18 libc++-18-dev libc++abi-18-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Configure & build (${{ matrix.arch }})
        run: |
          git clone --depth 1 https://github.com/tdlib/td.git
          mkdir -p td/build && cd td/build

          CMAKE_EXTRA=""
          if [ -n "${{ matrix.toolchain }}" ]; then
            CMAKE_EXTRA="-DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }}"
          fi

          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../tdlib \
            ${CMAKE_EXTRA}

          cmake --build . --target install -- -j$(nproc)


      #######################################################################
      # 4) Upload the freshly-built library (td/tdlib) so every PR and
      #    branch push has downloadable artefacts per architecture.
      #######################################################################
      - name: Upload libtdjson (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          # 👇 any name you like
          name: libtdjson-${{ matrix.arch }}
          # 👇 pick only the .so file, whatever its version suffix is
          path: td/tdlib/lib/libtdjson.so*
